# -*- coding: utf-8 -*-
"""
100種類のキャラクターデータを整形して js/data.js を生成するスクリプト
"""

CHARACTERS_100 = [
  # ----------------------------------------------------
  # 🦖 きょうりゅう・古代生物（25種類）
  # ----------------------------------------------------
  {
    "id": "tirano",
    "category": "dino",
    "nameHira": "てぃらの",
    "nameKata": "ティラノ",
    "charsHira": ["て", "ぃ", "ら", "の"],
    "charsKata": ["テ", "ィ", "ラ", "ノ"],
    "emoji": "🦖",
    "soundType": "roar",
    "soundText": "ガオーーッ！",
    "themeColor": "#ff6b6b",
    "actionType": "super-jump",
    "bgDecor": "🦴"
  },
  {
    "id": "torikera",
    "category": "dino",
    "nameHira": "とりけら",
    "nameKata": "トリケラ",
    "charsHira": ["と", "り", "け", "ら"],
    "charsKata": ["ト", "リ", "ケ", "ラ"],
    "emoji": "🦕",
    "soundType": "growl",
    "soundText": "ズシンズシン！",
    "themeColor": "#ffd166",
    "actionType": "dance-butt",
    "bgDecor": "🌿"
  },
  {
    "id": "putera",
    "category": "dino",
    "nameHira": "ぷてら",
    "nameKata": "プテラ",
    "charsHira": ["ぷ", "て", "ら"],
    "charsKata": ["プ", "テ", "ラ"],
    "emoji": "🦅",
    "soundType": "chirp",
    "soundText": "バサバサ〜！",
    "themeColor": "#06d6a0",
    "actionType": "high-jump",
    "bgDecor": "☁️"
  },
  {
    "id": "burakio",
    "category": "dino",
    "nameHira": "ぶらきお",
    "nameKata": "ブラキオ",
    "charsHira": ["ぶ", "ら", "き", "お"],
    "charsKata": ["ブ", "ラ", "キ", "オ"],
    "emoji": "🦕",
    "soundType": "trumpet",
    "soundText": "首がながーい！",
    "themeColor": "#118ab2",
    "actionType": "super-jump",
    "bgDecor": "🍃"
  },
  {
    "id": "sutego",
    "category": "dino",
    "nameHira": "すてご",
    "nameKata": "ステゴ",
    "charsHira": ["す", "て", "ご"],
    "charsKata": ["ス", "テ", "ゴ"],
    "emoji": "🦕",
    "soundType": "growl",
    "soundText": "トゲトゲかっこいい！",
    "themeColor": "#f78c6c",
    "actionType": "dance-butt",
    "bgDecor": "🌴"
  },
  {
    "id": "supino",
    "category": "dino",
    "nameHira": "すぴの",
    "nameKata": "スピノ",
    "charsHira": ["す", "ぴ", "の"],
    "charsKata": ["ス", "ピ", "ノ"],
    "emoji": "🦖",
    "soundType": "roar",
    "soundText": "お魚パクッ！",
    "themeColor": "#4ea8de",
    "actionType": "spin",
    "bgDecor": "🌊"
  },
  {
    "id": "ankiro",
    "category": "dino",
    "nameHira": "あんきろ",
    "nameKata": "アンキロ",
    "charsHira": ["あ", "ん", "き", "ろ"],
    "charsKata": ["ア", "ン", "キ", "ロ"],
    "emoji": "🦕",
    "soundType": "growl",
    "soundText": "しっぽハンマー！",
    "themeColor": "#70c1b3",
    "actionType": "dance-butt",
    "bgDecor": "🪨"
  },
  {
    "id": "raputoru",
    "category": "dino",
    "nameHira": "らぷとる",
    "nameKata": "ラプトル",
    "charsHira": ["ら", "ぷ", "と", "る"],
    "charsKata": ["ラ", "プ", "ト", "ル"],
    "emoji": "🦖",
    "soundType": "roar",
    "soundText": "すばやいぞ！",
    "themeColor": "#ffaa00",
    "actionType": "zoom-dash",
    "bgDecor": "🐾"
  },
  {
    "id": "aro",
    "category": "dino",
    "nameHira": "あろ",
    "nameKata": "アロ",
    "charsHira": ["あ", "ろ"],
    "charsKata": ["ア", "ロ"],
    "emoji": "🦖",
    "soundType": "roar",
    "soundText": "ガブッ！",
    "themeColor": "#e76f51",
    "actionType": "super-jump",
    "bgDecor": "🍖"
  },
  {
    "id": "mosa",
    "category": "dino",
    "nameHira": "もさ",
    "nameKata": "モサ",
    "charsHira": ["も", "さ"],
    "charsKata": ["モ", "サ"],
    "emoji": "🐋",
    "soundType": "snap",
    "soundText": "海の王者だ！",
    "themeColor": "#2a9d8f",
    "actionType": "spin",
    "bgDecor": "🫧"
  },
  {
    "id": "parasau",
    "category": "dino",
    "nameHira": "ぱらさう",
    "nameKata": "パラサウ",
    "charsHira": ["ぱ", "ら", "さ", "う"],
    "charsKata": ["パ", "ラ", "サ", "ウ"],
    "emoji": "🦕",
    "soundType": "trumpet",
    "soundText": "トサカでブォー！",
    "themeColor": "#e9c46a",
    "actionType": "high-jump",
    "bgDecor": "🎵"
  },
  {
    "id": "iguano",
    "category": "dino",
    "nameHira": "いぐあの",
    "nameKata": "イグアノ",
    "charsHira": ["い", "ぐ", "あ", "の"],
    "charsKata": ["イ", "グ", "ア", "ノ"],
    "emoji": "🦕",
    "soundType": "growl",
    "soundText": "親指トゲトゲ！",
    "themeColor": "#588157",
    "actionType": "jump",
    "bgDecor": "🌱"
  },
  {
    "id": "kaseki",
    "category": "dino",
    "nameHira": "かせき",
    "nameKata": "カセキ",
    "charsHira": ["か", "せ", "き"],
    "charsKata": ["カ", "セ", "キ"],
    "emoji": "🦴",
    "soundType": "cheer",
    "soundText": "たからもの発見！",
    "themeColor": "#d4a373",
    "actionType": "tap-bounce",
    "bgDecor": "⛏️"
  },
  {
    "id": "tamago",
    "category": "dino",
    "nameHira": "たまご",
    "nameKata": "タマゴ",
    "charsHira": ["た", "ま", "ご"],
    "charsKata": ["タ", "マ", "ゴ"],
    "emoji": "🥚",
    "soundType": "hop",
    "soundText": "パカッ！生まれた！",
    "themeColor": "#fefae0",
    "actionType": "jump",
    "bgDecor": "🐣"
  },
  {
    "id": "ryu",
    "category": "dino",
    "nameHira": "りゅう",
    "nameKata": "リュウ",
    "charsHira": ["り", "ゅ", "う"],
    "charsKata": ["リ", "ュ", "ウ"],
    "emoji": "🐲",
    "soundType": "roar",
    "soundText": "ドカーン！",
    "themeColor": "#e63946",
    "actionType": "super-jump",
    "bgDecor": "🔥"
  },
  {
    "id": "manmosu",
    "category": "dino",
    "nameHira": "まんもす",
    "nameKata": "マンモス",
    "charsHira": ["ま", "ん", "も", "す"],
    "charsKata": ["マ", "ン", "モ", "ス"],
    "emoji": "🦣",
    "soundType": "trumpet",
    "soundText": "パオーン！",
    "themeColor": "#bc6c25",
    "actionType": "dance-butt",
    "bgDecor": "❄️"
  },
  {
    "id": "dipuro",
    "category": "dino",
    "nameHira": "でぃぷろ",
    "nameKata": "ディプロ",
    "charsHira": ["で", "ぃ", "ぷ", "ろ"],
    "charsKata": ["デ", "ィ", "プ", "ロ"],
    "emoji": "🦕",
    "soundType": "growl",
    "soundText": "ながーいしっぽ！",
    "themeColor": "#83c5be",
    "actionType": "dance-butt",
    "bgDecor": "🌿"
  },
  {
    "id": "puresio",
    "category": "dino",
    "nameHira": "ぷれしお",
    "nameKata": "プレシオ",
    "charsHira": ["ぷ", "れ", "し", "お"],
    "charsKata": ["プ", "レ", "シ", "オ"],
    "emoji": "🦕",
    "soundType": "snap",
    "soundText": "首長竜スイスイ！",
    "themeColor": "#0077b6",
    "actionType": "spin",
    "bgDecor": "🌊"
  },
  {
    "id": "pakike",
    "category": "dino",
    "nameHira": "ぱきけ",
    "nameKata": "パキケ",
    "charsHira": ["ぱ", "き", "け"],
    "charsKata": ["パ", "キ", "ケ"],
    "emoji": "🦕",
    "soundType": "growl",
    "soundText": "頭がカチンコチン！",
    "themeColor": "#e07a5f",
    "actionType": "super-jump",
    "bgDecor": "💥"
  },
  {
    "id": "puterano",
    "category": "dino",
    "nameHira": "ぷてらの",
    "nameKata": "プテラノ",
    "charsHira": ["ぷ", "て", "ら", "の"],
    "charsKata": ["プ", "テ", "ラ", "ノ"],
    "emoji": "🦅",
    "soundType": "chirp",
    "soundText": "大空をひとっとび！",
    "themeColor": "#90be6d",
    "actionType": "high-jump",
    "bgDecor": "☁️"
  },
  {
    "id": "hadoro",
    "category": "dino",
    "nameHira": "はどろ",
    "nameKata": "ハドロ",
    "charsHira": ["は", "ど", "ろ"],
    "charsKata": ["ハ", "ド", "ロ"],
    "emoji": "🦕",
    "soundType": "trumpet",
    "soundText": "カモのはしご！",
    "themeColor": "#f9c74f",
    "actionType": "jump",
    "bgDecor": "🌾"
  },
  {
    "id": "megaro",
    "category": "dino",
    "nameHira": "めがろ",
    "nameKata": "メガロ",
    "charsHira": ["め", "が", "ろ"],
    "charsKata": ["メ", "ガ", "ロ"],
    "emoji": "🦈",
    "soundType": "snap",
    "soundText": "大きな古代サメ！",
    "themeColor": "#457b9d",
    "actionType": "spin",
    "bgDecor": "🌊"
  },
  {
    "id": "kiba",
    "category": "dino",
    "nameHira": "きば",
    "nameKata": "キバ",
    "charsHira": ["き", "ば"],
    "charsKata": ["キ", "バ"],
    "emoji": "🦷",
    "soundType": "roar",
    "soundText": "するどいキバ！",
    "themeColor": "#f8f9fa",
    "actionType": "jump",
    "bgDecor": "✨"
  },
  {
    "id": "tsuno",
    "category": "dino",
    "nameHira": "つの",
    "nameKata": "ツノ",
    "charsHira": ["つ", "の"],
    "charsKata": ["ツ", "ノ"],
    "emoji": "🦏",
    "soundType": "growl",
    "soundText": "つよいツノ！",
    "themeColor": "#e9ecef",
    "actionType": "super-jump",
    "bgDecor": "🛡️"
  },
  {
    "id": "hone",
    "category": "dino",
    "nameHira": "ほね",
    "nameKata": "ホネ",
    "charsHira": ["ほ", "ね"],
    "charsKata": ["ホ", "ネ"],
    "emoji": "🦴",
    "soundType": "cheer",
    "soundText": "おおきなホネ！",
    "themeColor": "#fff1e6",
    "actionType": "jump",
    "bgDecor": "🌟"
  },

  # ----------------------------------------------------
  # 🚒 はたらくくるま・乗り物（25種類）
  # ----------------------------------------------------
  {
    "id": "shobo",
    "category": "vehicle",
    "nameHira": "しょうぼう",
    "nameKata": "ショウボウ",
    "charsHira": ["し", "ょ", "う", "ぼ", "う"],
    "charsKata": ["シ", "ョ", "ウ", "ボ", "ウ"],
    "emoji": "🚒",
    "soundType": "horn",
    "soundText": "ウ〜カンカン！放水！",
    "themeColor": "#ff4d6d",
    "actionType": "zoom-dash",
    "bgDecor": "💦"
  },
  {
    "id": "patoka",
    "category": "vehicle",
    "nameHira": "ぱとかー",
    "nameKata": "パトカー",
    "charsHira": ["ぱ", "と", "か", "ー"],
    "charsKata": ["パ", "ト", "カ", "ー"],
    "emoji": "🚓",
    "soundType": "horn",
    "soundText": "ウ〜〜！パトロール！",
    "themeColor": "#3a86ff",
    "actionType": "zoom-dash",
    "bgDecor": "🚨"
  },
  {
    "id": "resukyu",
    "category": "vehicle",
    "nameHira": "れすきゅー",
    "nameKata": "レスキュー",
    "charsHira": ["れ", "す", "き", "ゅ", "ー"],
    "charsKata": ["レ", "ス", "キ", "ュ", "ー"],
    "emoji": "🚑",
    "soundType": "horn",
    "soundText": "ピーポーピーポー！",
    "themeColor": "#ff758f",
    "actionType": "zoom-dash",
    "bgDecor": "🩹"
  },
  {
    "id": "basu",
    "category": "vehicle",
    "nameHira": "ばす",
    "nameKata": "バス",
    "charsHira": ["ば", "す"],
    "charsKata": ["バ", "ス"],
    "emoji": "🚌",
    "soundType": "vroom",
    "soundText": "ぷっぷー！乗ってね！",
    "themeColor": "#ffb703",
    "actionType": "dance-butt",
    "bgDecor": "🚏"
  },
  {
    "id": "takushi",
    "category": "vehicle",
    "nameHira": "たくしー",
    "nameKata": "タクシー",
    "charsHira": ["た", "く", "し", "ー"],
    "charsKata": ["タ", "ク", "シ", "ー"],
    "emoji": "🚕",
    "soundType": "vroom",
    "soundText": "どこへ行きますか？",
    "themeColor": "#ffd166",
    "actionType": "zoom-dash",
    "bgDecor": "🚖"
  },
  {
    "id": "torakku",
    "category": "vehicle",
    "nameHira": "とらっく",
    "nameKata": "トラック",
    "charsHira": ["と", "ら", "っ", "く"],
    "charsKata": ["ト", "ラ", "ッ", "ク"],
    "emoji": "🚚",
    "soundType": "vroom",
    "soundText": "荷物を運ぶよ！",
    "themeColor": "#06d6a0",
    "actionType": "zoom-dash",
    "bgDecor": "📦"
  },
  {
    "id": "danpu",
    "category": "vehicle",
    "nameHira": "だんぷ",
    "nameKata": "ダンプ",
    "charsHira": ["だ", "ん", "ぷ"],
    "charsKata": ["ダ", "ン", "プ"],
    "emoji": "🚛",
    "soundType": "vroom",
    "soundText": "荷台がガッターン！",
    "themeColor": "#fb8500",
    "actionType": "dance-butt",
    "bgDecor": "🪨"
  },
  {
    "id": "shoberu",
    "category": "vehicle",
    "nameHira": "しょべる",
    "nameKata": "ショベル",
    "charsHira": ["し", "ょ", "べ", "る"],
    "charsKata": ["シ", "ョ", "ベ", "ル"],
    "emoji": "🚜",
    "soundType": "vroom",
    "soundText": "ガガガ！土を掘るよ！",
    "themeColor": "#ffbe0b",
    "actionType": "dance-butt",
    "bgDecor": "⛰️"
  },
  {
    "id": "kuren",
    "category": "vehicle",
    "nameHira": "くれーん",
    "nameKata": "クレーン",
    "charsHira": ["く", "れ", "ー", "ん"],
    "charsKata": ["ク", "レ", "ー", "ン"],
    "emoji": "🏗️",
    "soundType": "vroom",
    "soundText": "ウィーン！たかーい！",
    "themeColor": "#ff006e",
    "actionType": "super-jump",
    "bgDecor": "🧱"
  },
  {
    "id": "buru",
    "category": "vehicle",
    "nameHira": "ぶる",
    "nameKata": "ブル",
    "charsHira": ["ぶ", "る"],
    "charsKata": ["ブ", "ル"],
    "emoji": "🚜",
    "soundType": "vroom",
    "soundText": "ぐんぐん押すぞ！",
    "themeColor": "#ff9e00",
    "actionType": "zoom-dash",
    "bgDecor": "🚧"
  },
  {
    "id": "mikisa",
    "category": "vehicle",
    "nameHira": "みきさー",
    "nameKata": "ミキサー",
    "charsHira": ["み", "き", "さ", "ー"],
    "charsKata": ["ミ", "キ", "サ", "ー"],
    "emoji": "🚛",
    "soundType": "vroom",
    "soundText": "ぐるぐる回るよ！",
    "themeColor": "#43aa8b",
    "actionType": "spin",
    "bgDecor": "🌀"
  },
  {
    "id": "kisha",
    "category": "vehicle",
    "nameHira": "きしゃ",
    "nameKata": "キシャ",
    "charsHira": ["き", "し", "ゃ"],
    "charsKata": ["キ", "シ", "ャ"],
    "emoji": "🚂",
    "soundType": "vroom",
    "soundText": "シュッシュッポッポー！",
    "themeColor": "#2b2d42",
    "actionType": "zoom-dash",
    "bgDecor": "💨"
  },
  {
    "id": "densha",
    "category": "vehicle",
    "nameHira": "でんしゃ",
    "nameKata": "デンシャ",
    "charsHira": ["で", "ん", "し", "ゃ"],
    "charsKata": ["デ", "ン", "シ", "ャ"],
    "emoji": "🚃",
    "soundType": "vroom",
    "soundText": "ガタゴトガタゴト！",
    "themeColor": "#52b788",
    "actionType": "zoom-dash",
    "bgDecor": "🛤️"
  },
  {
    "id": "hikoki",
    "category": "vehicle",
    "nameHira": "ひこうき",
    "nameKata": "ヒコウキ",
    "charsHira": ["ひ", "こ", "う", "き"],
    "charsKata": ["ヒ", "コ", "ウ", "キ"],
    "emoji": "✈️",
    "soundType": "jet",
    "soundText": "ビュイーーーッ！",
    "themeColor": "#caf0f8",
    "actionType": "zoom-dash",
    "bgDecor": "☁️"
  },
  {
    "id": "heri",
    "category": "vehicle",
    "nameHira": "へり",
    "nameKata": "ヘリ",
    "charsHira": ["へ", "り"],
    "charsKata": ["ヘ", "リ"],
    "emoji": "🚁",
    "soundType": "jet",
    "soundText": "パタパタ空をとぶ！",
    "themeColor": "#e76f51",
    "actionType": "high-jump",
    "bgDecor": "🌤️"
  },
  {
    "id": "roketto",
    "category": "vehicle",
    "nameHira": "ろけっと",
    "nameKata": "ロケット",
    "charsHira": ["ろ", "け", "っ", "と"],
    "charsKata": ["ロ", "ケ", "ッ", "ト"],
    "emoji": "🚀",
    "soundType": "jet",
    "soundText": "３・２・１発射！",
    "themeColor": "#ff758f",
    "actionType": "super-jump",
    "bgDecor": "⭐"
  },
  {
    "id": "fune",
    "category": "vehicle",
    "nameHira": "ふね",
    "nameKata": "フネ",
    "charsHira": ["ふ", "ね"],
    "charsKata": ["フ", "ネ"],
    "emoji": "🚢",
    "soundType": "horn",
    "soundText": "ボォーーッ！波スイスイ！",
    "themeColor": "#8ecae6",
    "actionType": "dance-butt",
    "bgDecor": "⚓"
  },
  {
    "id": "boto",
    "category": "vehicle",
    "nameHira": "ぼーと",
    "nameKata": "ボート",
    "charsHira": ["ぼ", "ー", "と"],
    "charsKata": ["ボ", "ー", "ト"],
    "emoji": "🚤",
    "soundType": "vroom",
    "soundText": "びゅんびゅん走る！",
    "themeColor": "#00b4d8",
    "actionType": "zoom-dash",
    "bgDecor": "🌊"
  },
  {
    "id": "yotto",
    "category": "vehicle",
    "nameHira": "よっと",
    "nameKata": "ヨット",
    "charsHira": ["よ", "っ", "と"],
    "charsKata": ["ヨ", "ッ", "ト"],
    "emoji": "⛵",
    "soundType": "vroom",
    "soundText": "風にのってスイスイ！",
    "themeColor": "#90e0ef",
    "actionType": "dance-butt",
    "bgDecor": "🌬️"
  },
  {
    "id": "baiku",
    "category": "vehicle",
    "nameHira": "ばいく",
    "nameKata": "バイク",
    "charsHira": ["ば", "い", "く"],
    "charsKata": ["バ", "イ", "ク"],
    "emoji": "🏍️",
    "soundType": "vroom",
    "soundText": "ブルルン！はやい！",
    "themeColor": "#d90429",
    "actionType": "zoom-dash",
    "bgDecor": "🏁"
  },
  {
    "id": "kuruma",
    "category": "vehicle",
    "nameHira": "くるま",
    "nameKata": "クルマ",
    "charsHira": ["く", "る", "ま"],
    "charsKata": ["ク", "ル", "マ"],
    "emoji": "🚗",
    "soundType": "vroom",
    "soundText": "ブーーン！ドライブ！",
    "themeColor": "#ef233c",
    "actionType": "zoom-dash",
    "bgDecor": "🚦"
  },
  {
    "id": "sori",
    "category": "vehicle",
    "nameHira": "そり",
    "nameKata": "ソリ",
    "charsHira": ["そ", "り"],
    "charsKata": ["ソ", "リ"],
    "emoji": "🛷",
    "soundType": "vroom",
    "soundText": "雪の上をシューッ！",
    "themeColor": "#8338ec",
    "actionType": "zoom-dash",
    "bgDecor": "❄️"
  },
  {
    "id": "jipu",
    "category": "vehicle",
    "nameHira": "じーぷ",
    "nameKata": "ジープ",
    "charsHira": ["じ", "ー", "ぷ"],
    "charsKata": ["ジ", "ー", "プ"],
    "emoji": "🚙",
    "soundType": "vroom",
    "soundText": "山道もへっちゃら！",
    "themeColor": "#2b9348",
    "actionType": "jump",
    "bgDecor": "🌲"
  },
  {
    "id": "nozomi",
    "category": "vehicle",
    "nameHira": "のぞみ",
    "nameKata": "ノゾミ",
    "charsHira": ["の", "ぞ", "み"],
    "charsKata": ["ノ", "ゾ", "ミ"],
    "emoji": "🚅",
    "soundType": "jet",
    "soundText": "新幹線ビュイーン！",
    "themeColor": "#0077b6",
    "actionType": "zoom-dash",
    "bgDecor": "🚄"
  },
  {
    "id": "hayabusa",
    "category": "vehicle",
    "nameHira": "はやぶさ",
    "nameKata": "ハヤブサ",
    "charsHira": ["は", "や", "ぶ", "さ"],
    "charsKata": ["ハ", "ヤ", "ブ", "サ"],
    "emoji": "🚄",
    "soundType": "jet",
    "soundText": "みどり色の新幹線！",
    "themeColor": "#55a630",
    "actionType": "zoom-dash",
    "bgDecor": "⚡"
  },

  # ----------------------------------------------------
  # 🐶 どうぶつ・海の生き物（30種類）
  # ----------------------------------------------------
  {
    "id": "buta",
    "category": "animal",
    "nameHira": "ぶた",
    "nameKata": "ブタ",
    "charsHira": ["ぶ", "た"],
    "charsKata": ["ブ", "タ"],
    "emoji": "🐷",
    "soundType": "oink",
    "soundText": "ブヒブヒ〜♪",
    "themeColor": "#ffb3c6",
    "actionType": "dance-butt",
    "bgDecor": "🌸"
  },
  {
    "id": "inu",
    "category": "animal",
    "nameHira": "いぬ",
    "nameKata": "イヌ",
    "charsHira": ["い", "ぬ"],
    "charsKata": ["イ", "ヌ"],
    "emoji": "🐶",
    "soundType": "bark",
    "soundText": "ワンワン！",
    "themeColor": "#ffd166",
    "actionType": "jump",
    "bgDecor": "🦴"
  },
  {
    "id": "neko",
    "category": "animal",
    "nameHira": "ねこ",
    "nameKata": "ネコ",
    "charsHira": ["ね", "こ"],
    "charsKata": ["ネ", "コ"],
    "emoji": "🐱",
    "soundType": "meow",
    "soundText": "ニャーオ♪",
    "themeColor": "#cdb4db",
    "actionType": "spin",
    "bgDecor": "🐟"
  },
  {
    "id": "ushi",
    "category": "animal",
    "nameHira": "うし",
    "nameKata": "ウシ",
    "charsHira": ["う", "し"],
    "charsKata": ["ウ", "シ"],
    "emoji": "🐮",
    "soundType": "moo",
    "soundText": "モ〜〜ッ！",
    "themeColor": "#b7e4c7",
    "actionType": "dance-butt",
    "bgDecor": "🍀"
  },
  {
    "id": "kaeru",
    "category": "animal",
    "nameHira": "かえる",
    "nameKata": "カエル",
    "charsHira": ["か", "え", "る"],
    "charsKata": ["カ", "エ", "ル"],
    "emoji": "🐸",
    "soundType": "hop",
    "soundText": "ケロケロ〜♪",
    "themeColor": "#a7c957",
    "actionType": "high-jump",
    "bgDecor": "💧"
  },
  {
    "id": "panda",
    "category": "animal",
    "nameHira": "ぱんだ",
    "nameKata": "パンダ",
    "charsHira": ["ぱ", "ん", "だ"],
    "charsKata": ["パ", "ン", "ダ"],
    "emoji": "🐼",
    "soundType": "cheer",
    "soundText": "ヤッター！",
    "themeColor": "#e0aaff",
    "actionType": "dance-butt",
    "bgDecor": "🎋"
  },
  {
    "id": "lion",
    "category": "animal",
    "nameHira": "らいおん",
    "nameKata": "ライオン",
    "charsHira": ["ら", "い", "お", "ん"],
    "charsKata": ["ラ", "イ", "オ", "ン"],
    "emoji": "🦁",
    "soundType": "roar",
    "soundText": "ガオ〜〜ッ！",
    "themeColor": "#ffaa00",
    "actionType": "super-jump",
    "bgDecor": "👑"
  },
  {
    "id": "tora",
    "category": "animal",
    "nameHira": "とら",
    "nameKata": "トラ",
    "charsHira": ["と", "ら"],
    "charsKata": ["ト", "ラ"],
    "emoji": "🐯",
    "soundType": "roar",
    "soundText": "ガオーーッ！",
    "themeColor": "#ffb703",
    "actionType": "super-jump",
    "bgDecor": "🐾"
  },
  {
    "id": "zou",
    "category": "animal",
    "nameHira": "ぞう",
    "nameKata": "ゾウ",
    "charsHira": ["ぞ", "う"],
    "charsKata": ["ゾ", "ウ"],
    "emoji": "🐘",
    "soundType": "trumpet",
    "soundText": "パオ〜〜ン！",
    "themeColor": "#a2d2ff",
    "actionType": "dance-butt",
    "bgDecor": "💧"
  },
  {
    "id": "saru",
    "category": "animal",
    "nameHira": "さる",
    "nameKata": "サル",
    "charsHira": ["さ", "る"],
    "charsKata": ["サ", "ル"],
    "emoji": "🐵",
    "soundType": "cheer",
    "soundText": "ウキキ〜ッ！",
    "themeColor": "#e9c46a",
    "actionType": "spin",
    "bgDecor": "🍌"
  },
  {
    "id": "kuma",
    "category": "animal",
    "nameHira": "くま",
    "nameKata": "クマ",
    "charsHira": ["く", "ま"],
    "charsKata": ["ク", "マ"],
    "emoji": "🐻",
    "soundType": "growl",
    "soundText": "クマーーッ！",
    "themeColor": "#dda15e",
    "actionType": "dance-butt",
    "bgDecor": "🍯"
  },
  {
    "id": "usagi",
    "category": "animal",
    "nameHira": "うさぎ",
    "nameKata": "ウサギ",
    "charsHira": ["う", "さ", "ぎ"],
    "charsKata": ["ウ", "サ", "ギ"],
    "emoji": "🐰",
    "soundType": "hop",
    "soundText": "ピョンピョン！",
    "themeColor": "#ffcbf2",
    "actionType": "high-jump",
    "bgDecor": "🥕"
  },
  {
    "id": "tori",
    "category": "animal",
    "nameHira": "とり",
    "nameKata": "トリ",
    "charsHira": ["と", "り"],
    "charsKata": ["ト", "リ"],
    "emoji": "🐦",
    "soundType": "chirp",
    "soundText": "ピピピッ！",
    "themeColor": "#bde0fe",
    "actionType": "jump",
    "bgDecor": "🍃"
  },
  {
    "id": "uma",
    "category": "animal",
    "nameHira": "うま",
    "nameKata": "ウマ",
    "charsHira": ["う", "ま"],
    "charsKata": ["ウ", "マ"],
    "emoji": "🐴",
    "soundType": "vroom",
    "soundText": "ヒヒ〜〜ン！",
    "themeColor": "#e0aaff",
    "actionType": "zoom-dash",
    "bgDecor": "🌾"
  },
  {
    "id": "kirin",
    "category": "animal",
    "nameHira": "きりん",
    "nameKata": "キリン",
    "charsHira": ["き", "り", "ん"],
    "charsKata": ["キ", "リ", "ン"],
    "emoji": "🦒",
    "soundType": "cheer",
    "soundText": "首がながいね！",
    "themeColor": "#ffe3a8",
    "actionType": "jump",
    "bgDecor": "🌿"
  },
  {
    "id": "wani",
    "category": "animal",
    "nameHira": "わに",
    "nameKata": "ワニ",
    "charsHira": ["わ", "に"],
    "charsKata": ["ワ", "ニ"],
    "emoji": "🐊",
    "soundType": "snap",
    "soundText": "ガブガブ〜ッ！",
    "themeColor": "#99d98c",
    "actionType": "spin",
    "bgDecor": "🌊"
  },
  {
    "id": "shika",
    "category": "animal",
    "nameHira": "しか",
    "nameKata": "シカ",
    "charsHira": ["し", "か"],
    "charsKata": ["シ", "カ"],
    "emoji": "🦌",
    "soundType": "hop",
    "soundText": "ツノが立派！",
    "themeColor": "#cb997e",
    "actionType": "jump",
    "bgDecor": "🍁"
  },
  {
    "id": "risu",
    "category": "animal",
    "nameHira": "りす",
    "nameKata": "リス",
    "charsHira": ["り", "す"],
    "charsKata": ["リ", "ス"],
    "emoji": "🐿️",
    "soundType": "chirp",
    "soundText": "ドングリ大好き！",
    "themeColor": "#ddbea9",
    "actionType": "jump",
    "bgDecor": "🌰"
  },
  {
    "id": "hitsuji",
    "category": "animal",
    "nameHira": "ひつじ",
    "nameKata": "ヒツジ",
    "charsHira": ["ひ", "つ", "じ"],
    "charsKata": ["ヒ", "ツ", "ジ"],
    "emoji": "🐑",
    "soundType": "cheer",
    "soundText": "メェ〜！ふわふわ！",
    "themeColor": "#f8edeb",
    "actionType": "dance-butt",
    "bgDecor": "☁️"
  },
  {
    "id": "yagi",
    "category": "animal",
    "nameHira": "やぎ",
    "nameKata": "ヤギ",
    "charsHira": ["や", "ぎ"],
    "charsKata": ["ヤ", "ギ"],
    "emoji": "🐐",
    "soundType": "cheer",
    "soundText": "メェ〜！草モグモグ！",
    "themeColor": "#faedcd",
    "actionType": "jump",
    "bgDecor": "🍀"
  },
  {
    "id": "koara",
    "category": "animal",
    "nameHira": "こあら",
    "nameKata": "コアラ",
    "charsHira": ["こ", "あ", "ら"],
    "charsKata": ["コ", "ア", "ラ"],
    "emoji": "🐨",
    "soundType": "cheer",
    "soundText": "ユーカリ大好き！",
    "themeColor": "#d6ccc2",
    "actionType": "tap-bounce",
    "bgDecor": "🌿"
  },
  {
    "id": "gorira",
    "category": "animal",
    "nameHira": "ごりら",
    "nameKata": "ゴリラ",
    "charsHira": ["ご", "り", "ら"],
    "charsKata": ["ゴ", "リ", "ラ"],
    "emoji": "🦍",
    "soundType": "growl",
    "soundText": "ドンドン！胸をたたく！",
    "themeColor": "#6c757d",
    "actionType": "super-jump",
    "bgDecor": "🍌"
  },
  {
    "id": "sai",
    "category": "animal",
    "nameHira": "さい",
    "nameKata": "サイ",
    "charsHira": ["さ", "い"],
    "charsKata": ["サ", "イ"],
    "emoji": "🦏",
    "soundType": "growl",
    "soundText": "立派なツノ！",
    "themeColor": "#ced4da",
    "actionType": "dance-butt",
    "bgDecor": "🪨"
  },
  {
    "id": "kaba",
    "category": "animal",
    "nameHira": "かば",
    "nameKata": "カバ",
    "charsHira": ["か", "ば"],
    "charsKata": ["カ", "バ"],
    "emoji": "🦛",
    "soundType": "growl",
    "soundText": "お口アーン！",
    "themeColor": "#adb5bd",
    "actionType": "dance-butt",
    "bgDecor": "💦"
  },
  {
    "id": "rakuda",
    "category": "animal",
    "nameHira": "らくだ",
    "nameKata": "ラクダ",
    "charsHira": ["ら", "く", "だ"],
    "charsKata": ["ラ", "ク", "ダ"],
    "emoji": "🐪",
    "soundType": "cheer",
    "soundText": "背中にコブ！",
    "themeColor": "#d4a373",
    "actionType": "dance-butt",
    "bgDecor": "🏜️"
  },
  {
    "id": "kitsune",
    "category": "animal",
    "nameHira": "きつね",
    "nameKata": "キツネ",
    "charsHira": ["き", "つ", "ね"],
    "charsKata": ["キ", "ツ", "ネ"],
    "emoji": "🦊",
    "soundType": "chirp",
    "soundText": "コンコン！",
    "themeColor": "#f77f00",
    "actionType": "jump",
    "bgDecor": "🍂"
  },
  {
    "id": "penguin",
    "category": "animal",
    "nameHira": "ぺんぎん",
    "nameKata": "ペンギン",
    "charsHira": ["ぺ", "ん", "ぎ", "ん"],
    "charsKata": ["ペ", "ン", "ギ", "ン"],
    "emoji": "🐧",
    "soundType": "cheer",
    "soundText": "ヨチヨチ歩き！",
    "themeColor": "#003049",
    "actionType": "dance-butt",
    "bgDecor": "🧊"
  },
  {
    "id": "iruka",
    "category": "animal",
    "nameHira": "いるか",
    "nameKata": "イルカ",
    "charsHira": ["い", "る", "か"],
    "charsKata": ["イ", "ル", "カ"],
    "emoji": "🐬",
    "soundType": "chirp",
    "soundText": "キュイ！大ジャンプ！",
    "themeColor": "#48cae4",
    "actionType": "high-jump",
    "bgDecor": "🌊"
  },
  {
    "id": "kujira",
    "category": "animal",
    "nameHira": "くじら",
    "nameKata": "クジラ",
    "charsHira": ["く", "じ", "ら"],
    "charsKata": ["ク", "ジ", "ラ"],
    "emoji": "🐳",
    "soundType": "trumpet",
    "soundText": "潮をピュ〜〜ッ！",
    "themeColor": "#0077b6",
    "actionType": "super-jump",
    "bgDecor": "🫧"
  },
  {
    "id": "same",
    "category": "animal",
    "nameHira": "さめ",
    "nameKata": "サメ",
    "charsHira": ["さ", "め"],
    "charsKata": ["サ", "メ"],
    "emoji": "🦈",
    "soundType": "snap",
    "soundText": "海のスプリンター！",
    "themeColor": "#5c6b73",
    "actionType": "spin",
    "bgDecor": "🌊"
  },

  # ----------------------------------------------------
  # 🍎 たべもの・身近なモノ（20種類）
  # ----------------------------------------------------
  {
    "id": "ringo",
    "category": "food",
    "nameHira": "りんご",
    "nameKata": "リンゴ",
    "charsHira": ["り", "ん", "ご"],
    "charsKata": ["リ", "ン", "ゴ"],
    "emoji": "🍎",
    "soundType": "cheer",
    "soundText": "まっかなりんご！",
    "themeColor": "#e63946",
    "actionType": "jump",
    "bgDecor": "🍏"
  },
  {
    "id": "mikan",
    "category": "food",
    "nameHira": "みかん",
    "nameKata": "ミカン",
    "charsHira": ["み", "か", "ん"],
    "charsKata": ["ミ", "カ", "ン"],
    "emoji": "🍊",
    "soundType": "cheer",
    "soundText": "あまーいみかん！",
    "themeColor": "#f77f00",
    "actionType": "spin",
    "bgDecor": "🌱"
  },
  {
    "id": "banana",
    "category": "food",
    "nameHira": "ばなな",
    "nameKata": "バナナ",
    "charsHira": ["ば", "な", "な"],
    "charsKata": ["バ", "ナ", "ナ"],
    "emoji": "🍌",
    "soundType": "cheer",
    "soundText": "もぐもぐバナナ！",
    "themeColor": "#fcbf49",
    "actionType": "jump",
    "bgDecor": "🐒"
  },
  {
    "id": "suika",
    "category": "food",
    "nameHira": "すいか",
    "nameKata": "スイカ",
    "charsHira": ["す", "い", "か"],
    "charsKata": ["ス", "イ", "カ"],
    "emoji": "🍉",
    "soundType": "cheer",
    "soundText": "あまいすいか！",
    "themeColor": "#2a9d8f",
    "actionType": "jump",
    "bgDecor": "☀️"
  },
  {
    "id": "budo",
    "category": "food",
    "nameHira": "ぶどう",
    "nameKata": "ブドウ",
    "charsHira": ["ぶ", "ど", "う"],
    "charsKata": ["ブ", "ド", "ウ"],
    "emoji": "🍇",
    "soundType": "cheer",
    "soundText": "つぶつぶジューシー！",
    "themeColor": "#7209b7",
    "actionType": "jump",
    "bgDecor": "🍇"
  },
  {
    "id": "ichigo",
    "category": "food",
    "nameHira": "いちご",
    "nameKata": "イチゴ",
    "charsHira": ["い", "ち", "ご"],
    "charsKata": ["イ", "チ", "ゴ"],
    "emoji": "🍓",
    "soundType": "cheer",
    "soundText": "あまーいいちご！",
    "themeColor": "#f72585",
    "actionType": "jump",
    "bgDecor": "🍰"
  },
  {
    "id": "meron",
    "category": "food",
    "nameHira": "めろん",
    "nameKata": "メロン",
    "charsHira": ["め", "ろ", "ん"],
    "charsKata": ["メ", "ロ", "ン"],
    "emoji": "🍈",
    "soundType": "cheer",
    "soundText": "いいにおい！",
    "themeColor": "#99d98c",
    "actionType": "spin",
    "bgDecor": "✨"
  },
  {
    "id": "tomato",
    "category": "food",
    "nameHira": "とまと",
    "nameKata": "トマト",
    "charsHira": ["と", "ま", "と"],
    "charsKata": ["ト", "マ", "ト"],
    "emoji": "🍅",
    "soundType": "cheer",
    "soundText": "まあるいトマト！",
    "themeColor": "#d90429",
    "actionType": "jump",
    "bgDecor": "🥗"
  },
  {
    "id": "pan",
    "category": "food",
    "nameHira": "ぱん",
    "nameKata": "パン",
    "charsHira": ["ぱ", "ん"],
    "charsKata": ["パ", "ン"],
    "emoji": "🍞",
    "soundType": "cheer",
    "soundText": "焼きたてふかふか！",
    "themeColor": "#e9c46a",
    "actionType": "dance-butt",
    "bgDecor": "🥐"
  },
  {
    "id": "keki",
    "category": "food",
    "nameHira": "けーき",
    "nameKata": "ケーキ",
    "charsHira": ["け", "ー", "き"],
    "charsKata": ["ケ", "ー", "キ"],
    "emoji": "🎂",
    "soundType": "cheer",
    "soundText": "おいしいケーキ！",
    "themeColor": "#ffb703",
    "actionType": "jump",
    "bgDecor": "🎉"
  },
  {
    "id": "aisu",
    "category": "food",
    "nameHira": "あいす",
    "nameKata": "アイス",
    "charsHira": ["あ", "い", "す"],
    "charsKata": ["ア", "イ", "ス"],
    "emoji": "🍨",
    "soundType": "cheer",
    "soundText": "つめたくておいしい！",
    "themeColor": "#90e0ef",
    "actionType": "spin",
    "bgDecor": "🍦"
  },
  {
    "id": "purin",
    "category": "food",
    "nameHira": "ぷりん",
    "nameKata": "プリン",
    "charsHira": ["ぷ", "り", "ん"],
    "charsKata": ["プ", "リ", "ン"],
    "emoji": "🍮",
    "soundType": "cheer",
    "soundText": "ぷるぷるプリン！",
    "themeColor": "#f39c12",
    "actionType": "jump",
    "bgDecor": "🍮"
  },
  {
    "id": "ame",
    "category": "food",
    "nameHira": "あめ",
    "nameKata": "アメ",
    "charsHira": ["あ", "め"],
    "charsKata": ["ア", "メ"],
    "emoji": "🍬",
    "soundType": "cheer",
    "soundText": "あまいキャンディ！",
    "themeColor": "#ff4d6d",
    "actionType": "spin",
    "bgDecor": "🍭"
  },
  {
    "id": "onigiri",
    "category": "food",
    "nameHira": "おにぎり",
    "nameKata": "オニギリ",
    "charsHira": ["お", "に", "ぎ", "り"],
    "charsKata": ["オ", "ニ", "ギ", "リ"],
    "emoji": "🍙",
    "soundType": "cheer",
    "soundText": "モグモグおいしい！",
    "themeColor": "#333333",
    "actionType": "jump",
    "bgDecor": "🍘"
  },
  {
    "id": "sushi",
    "category": "food",
    "nameHira": "すし",
    "nameKata": "スシ",
    "charsHira": ["す", "し"],
    "charsKata": ["ス", "シ"],
    "emoji": "🍣",
    "soundType": "cheer",
    "soundText": "へい、おまち！",
    "themeColor": "#e63946",
    "actionType": "jump",
    "bgDecor": "🍵"
  },
  {
    "id": "kare",
    "category": "food",
    "nameHira": "かれー",
    "nameKata": "カレー",
    "charsHira": ["か", "れ", "ー"],
    "charsKata": ["カ", "レ", "ー"],
    "emoji": "🍛",
    "soundType": "cheer",
    "soundText": "おいしいカレー！",
    "themeColor": "#d4a373",
    "actionType": "jump",
    "bgDecor": "🥄"
  },
  {
    "id": "tsuki",
    "category": "food",
    "nameHira": "つき",
    "nameKata": "ツキ",
    "charsHira": ["つ", "き"],
    "charsKata": ["ツ", "キ"],
    "emoji": "🌙",
    "soundType": "cheer",
    "soundText": "おつきさまピカピカ！",
    "themeColor": "#f4a261",
    "actionType": "high-jump",
    "bgDecor": "⭐"
  },
  {
    "id": "hoshi",
    "category": "food",
    "nameHira": "ほし",
    "nameKata": "ホシ",
    "charsHira": ["ほ", "し"],
    "charsKata": ["ホ", "シ"],
    "emoji": "⭐",
    "soundType": "cheer",
    "soundText": "キラキラお星さま！",
    "themeColor": "#ffd166",
    "actionType": "spin",
    "bgDecor": "✨"
  },
  {
    "id": "niji",
    "category": "food",
    "nameHira": "にじ",
    "nameKata": "ニジ",
    "charsHira": ["に", "じ"],
    "charsKata": ["ニ", "ジ"],
    "emoji": "🌈",
    "soundType": "cheer",
    "soundText": "なないろの虹！",
    "themeColor": "#06d6a0",
    "actionType": "high-jump",
    "bgDecor": "☀️"
  },
  {
    "id": "taiyo",
    "category": "food",
    "nameHira": "たいよう",
    "nameKata": "タイヨウ",
    "charsHira": ["た", "い", "よ", "う"],
    "charsKata": ["タ", "イ", "ヨ", "ウ"],
    "emoji": "☀️",
    "soundType": "cheer",
    "soundText": "ポカポカお日さま！",
    "themeColor": "#e76f51",
    "actionType": "super-jump",
    "bgDecor": "🌻"
  }
]

import json

# 既存のKANA_TABLE_DATAなどを読み込む
with open('js/data.js', 'r', encoding='utf-8') as f:
  old_data = f.read()

# KANA_TABLE_DATA以降の部分を抽出
idx = old_data.find('// 2. 「おしゃべり 50おんずかん」50音表データ')
kana_part = old_data[idx:]

js_content = "// 4歳児向け知育ゲーム データ集（全100種類の言葉）\n\n"
js_content += "// 1. 「うごく！文字あつめ」データ（全100種類：きょうりゅう・はたらくくるま・どうぶつ・たべもの）\n"
js_content += "const CHARACTERS_DATA = " + json.dumps(CHARACTERS_100, ensure_ascii=False, indent=2) + ";\n\n"
js_content += "const RANDOM_DISTRACTORS_HIRA = ['あ', 'か', 'さ', 'た', 'な', 'は', 'ま', 'や', 'ら', 'わ', 'み', 'り', 'も', 'す', 'き'];\n"
js_content += "const RANDOM_DISTRACTORS_KATA = ['ア', 'カ', 'サ', 'タ', 'ナ', 'ハ', 'マ', 'ヤ', 'ラ', 'ワ', 'ミ', 'リ', 'モ', 'ス', 'キ'];\n\n"
js_content += kana_part

with open('js/data.js', 'w', encoding='utf-8') as f:
  f.write(js_content)

print("js/data.js updated with 100 characters successfully!")
